server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_base?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qwer@123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true