server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zeroyu/tensquare-config.git
  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456
management: #暴露触发消息总线的地址
  endpoints:
    web:
      exposure:
        include: bus-refresh