server:
  port: 9010
spring:
  application:
    name: tensquare‐friend #指定服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_friend?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Qwer@123456
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: itcast
eureka:
  client:
    service‐url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true