server:
  port: 9008
spring:
  application:
    name: tensquare-user

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_recruit?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qwer@123456

  redis:
    host: 39.105.37.77

  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456

  jpa:
    database: mysql
    show-sql: true