server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Qwer@123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
eureka:
  client:
    service-url:
      defaultZone: http://39.105.37.77:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 39.105.37.77