server: 
  port: 9002
spring: 
  application:  
    name: tensquare-recruit #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_recruit?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Qwer@123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456
eureka:
  client:
    service-url:
      defaultZone: http://39.105.37.77:6868/eureka/
  instance:
    prefer-ip-address: true