server:
  port: 9007
spring:
  application:
    name: tensquare-search
  data:
    elasticsearch:
      cluster-nodes: 39.105.37.77:9300
  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456
eureka:
  client:
    service-url:
      defaultZone: http://39.105.37.77:6868/eureka/
  instance:
    prefer-ip-address: true