server:
  port: 9006
spring:
  application:
    name: tensquare-spit
  data:
    mongodb:
      host: 39.105.37.77
      database: spitdb
  redis:
    port: 6379
    host: 39.105.37.77
  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456
eureka:
  client:
    service-url:
      defaultZone: http://39.105.37.77:6868/eureka/
  instance:
    prefer-ip-address: true