server:
  port: 9008
spring:
  application:
    name: tensquare-user

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.37.77:3306/tensquare_user?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Qwer@123456

  redis:
    host: 39.105.37.77

  rabbitmq:
    host: 39.105.37.77
    username: root
    password: Qwer@123456

  jpa:
    database: mysql
    show-sql: true
    open-in-view: true

  #时区和时间格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://39.105.37.77:6868/eureka/
  instance:
    prefer-ip-address: true